// Code generated by mockery v2.30.16. DO NOT EDIT.

package client

import (
	context "context"

	external "github.com/kozmod/omni/external"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// mockService is an autogenerated mock type for the Service type
type mockService struct {
	mock.Mock
}

// GetLimits provides a mock function with given fields:
func (_m *mockService) GetLimits() (uint64, time.Duration) {
	ret := _m.Called()

	var r0 uint64
	var r1 time.Duration
	if rf, ok := ret.Get(0).(func() (uint64, time.Duration)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() time.Duration); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	return r0, r1
}

// Process provides a mock function with given fields: ctx, batch
func (_m *mockService) Process(ctx context.Context, batch external.Batch) error {
	ret := _m.Called(ctx, batch)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, external.Batch) error); ok {
		r0 = rf(ctx, batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockService creates a new instance of mockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockService {
	mock := &mockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
